{% set version = "7.3.0" %}

package:
  name: pytest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest/pytest-{{ version }}.tar.gz
  sha256: 58ecc27ebf0ea643ebfdf7fb1249335da761a00c9f955bcd922349bcb68ee57d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pytest = pytest:console_main
    - py.test = pytest:console_main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0
    - setuptools_scm >=6.0
  run:
    - python >=3.8
    - attrs >=19.2.0
    - iniconfig
    - packaging
    - pluggy >=0.12,<2.0
    - tomli >=1.0.0
    # colorama is needed only for windows, but okay to have for unix
    # For eg: tqdm does the same thing
    - colorama
    # exceptiongroup should be only [py<311] but let's see if we can keep this noarch.
    - exceptiongroup
  run_constrained:
    # pytest-faulthandler 2 is a dummy package.
    # if an older version of fault-handler is installed, it will conflict with pytest >=5.
    - pytest-faulthandler >=2

test:
  commands:
    - pytest -h
  imports:
    - pytest

about:
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
