{% set version = "7.2.0" %}

package:
  name: pytest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest/pytest-{{ version }}.tar.gz
  sha256: c4014eb40e10f11f355ad4e3c2fb2c6c6d1919c73f3b5a433de4708202cade59

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pytest = pytest:console_main
    - py.test = pytest:console_main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=42.0
    - setuptools_scm >=6.0
  run:
    - python
    - attrs >=19.2.0
    - iniconfig
    - packaging
    - pluggy >=0.12,<2.0
    - colorama  # [win]
    - exceptiongroup  # [py<311]    
    - importlib-metadata >=0.12  # [py<38]
    - tomli >=1.0.0
  run_constrained:
    # pytest-faulthandler 2 is a dummy package.
    # if an older version of fault-handler is installed, it will conflict with pytest >=5.
    - pytest-faulthandler >=2

test:
  commands:
    - pytest -h
  imports:
    - pytest

about:
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
